version: "3"
services:
  support-tools:
    build: .
    ports:
      - "3001:3000"
    container_name: support-tools
    volumes:
      - ./support-tools:/usr/src/app/next
    command: npm run dev

  sample-function:
    tty: true
    build: 
      context: ./lambda/SampleFunction/
      dockerfile: Dockerfile
    ports:
      - 9000:8080
    environment:
      - AWS_DEFAULT_REGION="ap-northeast-1"
      - AWS_ACCESS_KEY_ID="<your-aws-access-key-id>"
      - AWS_SECRET_ACCESS_KEY="<your-aws-secret-acess-key>"
      - DB_DATABASE=hello_flask_dev
      - DB_USER=hello_flask
      - DB_PASS=hello_flask
      - HOST_NAME=old-support-tools_db_1
    # command: /entry.sh /main

# oldと同一のDBを使うようにnetworkを設定する
networks:
  default:
    name: old-support-tools_default
    external: true