version: "3"
services:
  support-tools:
    build: .
    ports:
      - "3001:3000"
    container_name: support-tools
    volumes:
      - ./support-tools:/usr/src/app/next
    command: npm run dev

  sample-function:
    tty: true
    build: 
      context: ./lambda/SampleFunction/
      dockerfile: Dockerfile
    ports:
      - 9000:8080
    environment:
      - AWS_DEFAULT_REGION="ap-northeast-1"
      - AWS_ACCESS_KEY_ID="<your-aws-access-key-id>"
      - AWS_SECRET_ACCESS_KEY="<your-aws-secret-acess-key>"
    command: /entry.sh /main